[package]
name = "weatherbot-rust-c-wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
open-meteo-api = "=0.1.4"
reqwest = "0.12.4"
serde = "1.0.203"
serde_json = "1.0.117"
tokio = "1.38.0"

[lib]
crate-type =["cdylib"]
